{{ if .Values.app.config.configMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.app.config.configMap.name }}"
  namespace: "{{ .Values.app.config.configMap.namespace }}"
data:
  values: |
    {{ .Values.configMap.values }}
{{ end }}
