apiVersion: application.giantswarm.io/v1alpha1
kind: AppCatalog
metadata:
  annotations:
    giantswarm.io/docs: https://pkg.go.dev/github.com/giantswarm/apiextensions/pkg/apis/application/v1alpha1?tab=doc#AppCatalog
  creationTimestamp: null
  name: my-app-catalog
spec:
  config:
    configMap:
      name: my-playground-catalog
      namespace: my-namespace
    secret:
      name: my-playground-catalog
      namespace: my-namespace
  description: Applications we provide for all sorts of purposes.
  logoURL: https://my-org.github.com/logo.png
  storage:
    URL: https://my-org.github.com/my-app-catalog/
    type: helm
  title: My App Catalog
