apiVersion: application.giantswarm.io/v1alpha1
kind: AppCatalogEntry
metadata:
  creationTimestamp: null
  name: giantswarm-nginx-ingress-controller-app-1.9.2
  namespace: default
spec:
  appName: nginx-ingress-controller-app
  appVersion: v0.35.0
  catalog:
    name: giantswarm
    namespace: ""
  chart:
    apiVersion: v1
    home: https://github.com/giantswarm/nginx-ingress-controller-app
    icon: https://upload.wikimedia.org/wikipedia/commons/nginx-logo.svg
  dateCreated: "2020-09-02T09:40:39Z"
  dateUpdated: "2020-09-02T09:40:39Z"
  restrictions:
    clusterSingleton: true
    compatibleProviders:
    - aws
    fixedNamespace: giantswarm
  version: 1.9.2
