apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/reference/cp-k8s-api/apps.application.giantswarm.io/
  creationTimestamp: null
  name: c68pn-prometheus
spec:
  cert:
    allowBareDomains: false
    altNames: []
    clusterComponent: prometheus
    clusterID: c68pn
    commonName: api.c68pn.k8s.gollum.westeurope.azure.gigantic.io
    disableRegeneration: false
    ipSans: []
    organizations: []
    ttl: 4320h
  versionBundle:
    version: 0.1.0
