apiVersion: infrastructure.giantswarm.io/v1alpha2
kind: AWSMachineDeployment
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/reference/cp-k8s-api/awsmachinedeployments.infrastructure.giantswarm.io/
  creationTimestamp: null
  name: general-purpose-node-pool
spec:
  nodePool:
    description: General purpose worker nodes
    machine:
      dockerVolumeSizeGB: 30
      kubeletVolumeSizeGB: 100
    scaling:
      max: 50
      min: 2
  provider:
    availabilityZones:
    - eu-central-1b
    - eu-central-1c
    instanceDistribution:
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    worker:
      instanceType: m5.4xlarge
      useAlikeInstanceTypes: true
