- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/metadata
  value:
    properties:
      name:
        type: string
        pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-[1-9a-z]*)?$
    type: object
