
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: appcatalogentries.application.giantswarm.io
spec:
  group: application.giantswarm.io
  names:
    categories:
    - common
    - giantswarm
    kind: AppCatalogEntry
    listKind: AppCatalogEntryList
    plural: appcatalogentries
    shortNames:
    - ace
    - aces
    singular: appcatalogentry
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Catalog this entry belongs to
      jsonPath: .spec.catalog.name
      name: Catalog
      type: string
    - description: App this entry belongs to
      jsonPath: .spec.appName
      name: App Name
      type: string
    - description: Version of the app for this entry
      jsonPath: .spec.version
      name: Version
      type: string
    - description: Upstream version of the app for this entry
      jsonPath: .spec.appVersion
      name: Upstream Version
      type: string
    - description: Time since entry was first created
      jsonPath: .spec.dateCreated
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AppCatalogEntry represents an entry of an app in a catalog of
          managed apps. It stores metadata for specific versions and apps. It is generated
          by app-operator and consumed by app-admission-controller.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              appName:
                description: AppName is the name of the app this entry belongs to.
                  e.g. nginx-ingress-controller-app
                type: string
              appVersion:
                description: AppVersion is the upstream version of the app for this
                  entry. e.g. v0.35.0
                type: string
              catalog:
                description: Catalog is the name of the app catalog this entry belongs
                  to. e.g. giantswarm
                properties:
                  name:
                    description: Name is the name of the app catalog this entry belongs
                      to. e.g. giantswarm-catalog
                    type: string
                  namespace:
                    description: Namespace is the namespace of the catalog.
                    type: string
                required:
                - name
                type: object
              chart:
                description: Chart is metadata from the Chart.yaml of the app this
                  entry belongs to.
                properties:
                  apiVersion:
                    description: APIVersion is the Helm chart API version.
                    type: string
                  description:
                    description: Description is the Helm chart description.
                    nullable: true
                    type: string
                  home:
                    description: Home is the URL of this projects home page.
                    nullable: true
                    type: string
                  icon:
                    description: Icon is a URL to an SVG or PNG image to be used as
                      an icon.
                    nullable: true
                    type: string
                  keywords:
                    description: Keywords is the keyword strings from the helm chart.
                    items:
                      type: string
                    nullable: true
                    type: array
                  upstreamChartVersion:
                    description: UpstreamChartVersion is the original version of upstream
                      chart in this app.
                    nullable: true
                    type: string
                required:
                - apiVersion
                type: object
              dateCreated:
                description: DateCreated is when this entry was first created. e.g.
                  2020-09-02T09:40:39.223638219Z
                format: date-time
                type: string
              dateUpdated:
                description: DateUpdated is when this entry was last updated. e.g.
                  2020-09-02T09:40:39.223638219Z
                format: date-time
                type: string
              restrictions:
                description: Restrictions is metadata from Chart.yaml for this app
                  and is used to validate app CRs.
                nullable: true
                properties:
                  clusterSingleton:
                    description: ClusterSingleton is a flag for whether this app can
                      be installed at most once per cluster. Default is false.
                    type: boolean
                  compatibleProviders:
                    description: CompatibleProviders is a list of provider names which
                      this app is compatible with. Default is empty. Empty list means
                      app is compatible with all providers.
                    items:
                      type: string
                    nullable: true
                    type: array
                  fixedNamespace:
                    description: FixedNamespace is the namespace which this app must
                      be installed in.
                    type: string
                  gpuInstances:
                    description: GpuInstances is a flag for whether this app requires
                      GPU instances to run. Default is false.
                    type: boolean
                  namespaceSingleton:
                    description: NamespaceSingleton is a flag for whether this app
                      can be installed at most once per namespace. Default is false.
                    type: boolean
                type: object
              version:
                description: Version is the version of the app chart for this entry.
                  e.g. 1.9.2
                type: string
            required:
            - appName
            - appVersion
            - catalog
            - dateCreated
            - dateUpdated
            - version
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
