apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: apps.application.giantswarm.io
spec:
  group: application.giantswarm.io
  names:
    kind: App
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: |
        Defines an App resource, which represents an application to be running in a Kubernetes cluster.
        Reconciled by app-operator running on the Control Plane cluster.
      properties:
        spec:
          properties:
            catalog:
              description: |
                Name of the AppCatalog resource to install this app from. The AppCatalog resource must
                exist upfront in the cluster.
              type: string
            config:
              description: |
                Cluster configuration details for the application injected by cluster-operator with basic
                information of the cluster where the App is deployed. 
              properties:
                configMap:
                  description: |
                    Defines a reference to a ConfigMap where is saved the cluster configuration values 
                    that will be applied to the application when it is deployed in the cluster. 
                  properties:
                    name:
                      description: |
                        Name of the ConfigMap resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the ConfigMap resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                secret:
                  description: |
                    Defines the reference of a Secret where is saved the sensitive configuration
                    that will be applied to the application when it is deployed in the cluster.
                  properties:
                    name:
                      description: |
                        Name of the Secret resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the Secret resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
              type: object
            kubeConfig:
              description: |
                The kubeconfig to use to connect to the cluster when deploying the app.
              properties:
                context:
                  description: |
                    Kubeconfig context part to use when not using inCluster credentials.
                  properties:
                    name:
                      description: |
                        Context name.
                      type: string
                  type: object
                inCluster:
                  description: |
                    Defines whether to use inCluster credentials. If true, it uses the service account to 
                    authenticate against the Kubernetes API in the same cluster where the app-operator
                    is running. In that case, the context and secret properties must not be set. If false,
                    secret and context is used by the app-operator to access the external cluster API.
                  type: boolean
                secret:
                  description: |
                    Defines the reference to a Secret where is saved the kubeconfig configuration
                    that will be applied when accessing the cluster to manage the application.
                  properties:
                    name:
                      description: |
                        Name of the Secret resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the Secret resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
              type: object
            name:
              description: |
                Name of this App.
              type: string
            namespace:
              description: |
                Kubernetes namespace in which to install the workloads defined by this App in the 
                given cluster.
              type: string
            userConfig:
              description: |
                User configuration for the App. This configuration will be merged with the catalog and
                cluster configuration to generate a single values ConfigMap in the target cluster.
              properties:
                configMap:
                  description: |
                    Defines the reference of a ConfigMap where is saved the user configuration values 
                    that will be applied to the application when it is deployed in the cluster. 
                  properties:
                    name:
                      description: |
                        Name of the ConfigMap resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the ConfigMap resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                secret:
                  description: |
                    Defines the reference of a Secret where is saved the user sensitive configuration 
                    that will be applied to the application when it is deployed in the cluster. 
                  properties:
                    name:
                      description: |
                        Name of the Secret resource.
                      type: string
                    namespace:
                      description: |
                        Namespace holding the Secret resource.
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
              type: object
            version:
              description: |
                Version of the app to be deployed. It must exist within the list of App packages
                stored in the App Catalog.
              type: string
          required:
          - catalog
          - name
          - namespace
          - version
          type: object
      type: object
  version: v1alpha1
