apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: certconfigs.core.giantswarm.io
spec:
  conversion:
    strategy: None
  group: core.giantswarm.io
  names:
    kind: CertConfig
    listKind: CertConfigList
    plural: certconfigs
    singular: certconfig
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |
          The CertConfig resource is used in a Giant Swarm installation to ensure TLS communication between
          a component (e. g. prometheus) and the tenant cluster nodes. It is reconciled by cert-operator.
          For each CertConfig resource, cert-operator ensures the existence of an X.509 certificate as
          defined in RFC 5280.
        properties:
          spec:
            properties:
              cert:
                description: |
                  Defines an X.509 certificate to be ensured by cert-operator.
                properties:
                  allowBareDomains:
                    description: |
                      Specifies if clients can request certificates matching the value of the actual
                      domains themselves.
                    type: bool
                  altNames:
                    description: |
                      Specifies host names to set in the certificate as Subject Alternative Names.
                    items:
                      type: string
                    type: array
                  clusterComponent:
                    description: |
                      Name of the component this certificate is for.
                    type: string
                  clusterID:
                    description: |
                      Unique identifier of the tenant cluster this certificate is for.
                    type: string
                  commonName:
                    description: |
                      The value of the Common Name (CN) attribute of the certificate.
                  disableRegeneration:
                    description: |
                      Toggles the automatic recreation before expiry.
                    type: bool
                  ipSans:
                    description: |
                      Specifies requested IP Subject Alternative Names to be set in the
                      certificate.
                    items:
                      type: string
                    type: array
                  organizations:
                    description: |
                      Organizations to set in the Organizations (O) attribute of the
                      certificate.
                    items:
                      type: string
                    type: array
                  ttl:
                    description: |
                      Expiry duration after creation. The value must consist of a number
                      combined with a unit, without blanks, to be parsed by the Go
                      [time.ParseDuration](https://golang.org/pkg/time/#ParseDuration) function.
                    type: string
                type: object
              versionBundle:
                description: |
                  No longer used
                type: object
            type: object
    served: true
    storage: true
