apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: releases.release.giantswarm.io
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            creationTimestamp:
              type: string
              pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$
