- op: replace
  path: /spec/validation/openAPIV3Schema/properties/spec/properties/template/properties/spotVMOptions/properties/maxPrice
  value:
    anyOf:
    - type: integer
    - type: string
    description: MaxPrice defines the maximum price the user is
      willing to pay for Spot VM instances
    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
    x-kubernetes-int-or-string: true
