clusterName: "test-cluster"
commonDomain: "aws.gigantic.io"
sshUser: "test-user"
sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAYQCurvzg5Ia54kb3NZapA6yP00//+Jt6XJNeC7Seq3TeCqMR9x7Snalj19r0lWok1PkRgDo1PXj+3y53zo/wqBrPqN4cQqp00R06kNfnhAgesaRMvYhuyVRQQbfXV5gQg8M= dummy-key"
encryptionKey: "QitRZGlWeW5WOFo2YmdvMVRwQUQ2UWoxRHZSVEF4MmovajlFb05sT1AzOD0="
versionBundleVersion: "0.1.0"
updateEnabled: true
aws:
  region: "eu-central-1"
  az: "eu-central-1a"
  ami: "ami-d60ad6b9"
  instanceTypeMaster: "m3.large"
  instanceTypeWorker: "m3.large"

  networkCIDR: "10.1.12.0/24"
  privateSubnetCIDR: "10.1.12.0/25"
  publicSubnetCIDR: "10.1.12.128/25"

  apiHostedZone: "Z*************"
  ingressHostedZone: "Z*************"
  routeTable0: "example-table"
  routeTable1: "example-table-two"
  vpcPeerId: "vpc-XXXXXXXXX"

  credentialName: "credential-default"
  credentialNamespace: "giantswarm"