
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: appcatalogentries.application.giantswarm.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.catalog.name
    description: Catalog this entry belongs to
    name: Catalog
    type: string
  - JSONPath: .spec.appName
    description: App this entry belongs to
    name: App Name
    type: string
  - JSONPath: .spec.appVersion
    description: Upstream version of the app for this entry
    name: App Version
    type: string
  - JSONPath: .spec.version
    description: Version of the app for this entry
    name: Version
    type: string
  - JSONPath: .spec.dateCreated
    description: Time since entry was first created
    name: Age
    type: date
  group: application.giantswarm.io
  names:
    categories:
    - common
    - giantswarm
    kind: AppCatalogEntry
    listKind: AppCatalogEntryList
    plural: appcatalogentries
    singular: appcatalogentry
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: AppCatalogEntry represents an entry of an app in a catalog of managed
        apps.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appName:
              description: AppName is the name of the app this entry belongs to. e.g.
                nginx-ingress-controller-app
              type: string
            appVersion:
              description: AppVersion is the upstream version of the app for this
                entry. e.g. v0.35.0
              type: string
            catalog:
              description: Catalog is the name of the app catalog this entry belongs
                to. e.g. giantswarm
              properties:
                name:
                  description: Name is the name of the app catalog this entry belongs
                    to. e.g. giantswarm-catalog
                  type: string
                namespace:
                  description: Namespace is the namespace of the catalog. It is empty
                    while the appcatalog CRD is cluster scoped.
                  type: string
              required:
              - name
              type: object
            chart:
              description: Chart is metadata from the Chart.yaml of the app this entry
                belongs to.
              properties:
                home:
                  description: Home is the URL of this projects home page.
                  nullable: true
                  type: string
                icon:
                  description: Icon is a URL to an SVG or PNG image to be used as
                    an icon.
                  nullable: true
                  type: string
              type: object
            dateCreated:
              description: DateCreated is when this entry was first created. e.g.
                2020-09-02T09:40:39.223638219Z
              format: date-time
              type: string
            dateUpdated:
              description: DateUpdated is when this entry was last updated. e.g. 2020-09-02T09:40:39.223638219Z
              format: date-time
              type: string
            restrictions:
              description: Restrictions is metadata from Chart.yaml for this app and
                is used to validate app CRs.
              nullable: true
              properties:
                cluster_singleton:
                  description: ClusterSingleton is a flag for whether this app can
                    be installed at most once per cluster.
                  type: boolean
                fixed_namespace:
                  description: FixedNamespace is the namespace which this app must
                    be installed in.
                  type: string
                gpu_instances:
                  description: GpuInstances is a flag for whether this app requires
                    GPU instances to run.
                  type: boolean
                namespace_singleton:
                  description: NamespaceSingleton is a flag for whether this app can
                    be installed at most once per namespace.
                  type: boolean
              required:
              - cluster_singleton
              - gpu_instances
              - namespace_singleton
              type: object
            version:
              description: Version is the version of the app chart for this entry.
                e.g. 1.9.2
              type: string
          required:
          - appName
          - appVersion
          - catalog
          - dateCreated
          - dateUpdated
          - version
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
