
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: kvmclusters.infrastructure.giantswarm.io
spec:
  group: infrastructure.giantswarm.io
  names:
    categories:
    - giantswarm
    - kvm
    kind: KVMCluster
    listKind: KVMClusterList
    plural: kvmclusters
    singular: kvmcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KVMCluster is the infrastructure provider referenced in upstream
        Cluster API Cluster CRs for the Giant Swarm KVM platform.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KVMClusterSpec is the spec part for the KVMCluster resource.
          properties:
            cluster:
              description: Cluster specification details.
              properties:
                description:
                  description: User-friendly description that should explain the purpose
                    of the cluster to humans.
                  type: string
                dns:
                  description: DNS configuration details.
                  properties:
                    domain:
                      type: string
                  required:
                  - domain
                  type: object
              required:
              - description
              - dns
              type: object
            controlPlaneEndpoint:
              description: Endpoint used to connect to the target cluster's Kubernetes
                API server.
              properties:
                host:
                  description: The hostname on which the API server is serving.
                  type: string
                port:
                  description: The port on which the API server is serving.
                  format: int32
                  type: integer
              required:
              - host
              - port
              type: object
            provider:
              description: Provider-specific configuration details.
              properties:
                endpointUpdaterImage:
                  type: string
                flannelVNI:
                  type: integer
                machineImage:
                  type: string
                machineStorageType:
                  type: string
                portMappings:
                  items:
                    properties:
                      name:
                        type: string
                      nodePort:
                        type: integer
                      targetPort:
                        type: integer
                    required:
                    - name
                    - nodePort
                    - targetPort
                    type: object
                  type: array
              required:
              - endpointUpdaterImage
              - flannelVNI
              - machineImage
              - machineStorageType
              - portMappings
              type: object
          required:
          - cluster
          - controlPlaneEndpoint
          - provider
          type: object
        status:
          description: AWSClusterStatus holds status information about the cluster,
            populated once the cluster is in creation or created.
          properties:
            cluster:
              description: Cluster-specific status details, including conditions and
                versions.
              properties:
                conditions:
                  description: One or several conditions that are currently applicable
                    to the cluster.
                  items:
                    description: CommonClusterStatusCondition explains the current
                      condition(s) of the cluster.
                    properties:
                      condition:
                        description: Condition string, e. g. `Creating`, `Created`,
                          `Upgraded`.
                        type: string
                      lastTransitionTime:
                        description: Time the condition occurred.
                        format: date-time
                        type: string
                    type: object
                  type: array
                id:
                  description: Identifier of the cluster.
                  type: string
                versions:
                  description: Release versions the cluster used so far.
                  items:
                    description: CommonClusterStatusVersion informs which aws-operator
                      version was/responsible for this cluster.
                    properties:
                      lastTransitionTime:
                        description: Time the cluster assumed the given version.
                        format: date-time
                        type: string
                      version:
                        description: The aws-operator version responsible for handling
                          the cluster.
                        type: string
                    type: object
                  type: array
              type: object
            provider:
              description: Provider-specific status details.
              properties:
                network:
                  description: Network-specific configuration details
                  properties:
                    cidr:
                      description: IPv4 address block used by the workload cluster
                        nodes, in CIDR notation.
                      type: string
                    vpcID:
                      description: Identifier of the AWS Virtual Private Cloud (VPC)
                        of the workload cluster, e.g. `vpc-1234567890abcdef0`.
                      type: string
                  type: object
              type: object
            ready:
              description: True when the infrastructure is ready to be used.
              type: boolean
          type: object
      required:
      - metadata
      - spec
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
