
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: apps.application.giantswarm.io
spec:
  group: application.giantswarm.io
  names:
    categories:
    - common
    - giantswarm
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Version of the app
      jsonPath: .spec.version
      name: Version
      type: string
    - description: Time since last deployment
      jsonPath: .status.release.lastDeployed
      name: Last Deployed
      type: date
    - description: Deployment status of the app
      jsonPath: .status.release.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: App represents a managed app which a user intended to install.
          It is reconciled by app-operator.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              catalog:
                description: Catalog is the name of the app catalog this app belongs
                  to. e.g. giantswarm
                type: string
              catalogNamespace:
                description: CatalogNamespace is the namespace of the Catalog CR this
                  app belongs to. e.g. giantswarm
                nullable: true
                type: string
              config:
                description: Config is the config to be applied when the app is deployed.
                nullable: true
                properties:
                  configMap:
                    description: ConfigMap references a config map containing values
                      that should be applied to the app.
                    nullable: true
                    properties:
                      name:
                        description: Name is the name of the config map containing
                          app values to apply, e.g. prometheus-values.
                        type: string
                      namespace:
                        description: Namespace is the namespace of the values config
                          map, e.g. monitoring.
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                  secret:
                    description: Secret references a secret containing secret values
                      that should be applied to the app.
                    nullable: true
                    properties:
                      name:
                        description: Name is the name of the secret containing app
                          values to apply, e.g. prometheus-secret.
                        type: string
                      namespace:
                        description: Namespace is the namespace of the secret, e.g.
                          kube-system.
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                type: object
              install:
                description: Install is the config used when installing the app.
                nullable: true
                properties:
                  skipCRDs:
                    description: 'SkipCRDs when true decides that CRDs which are supplied
                      with the chart are not installed. Default: false.'
                    nullable: true
                    type: boolean
                type: object
              kubeConfig:
                description: KubeConfig is the kubeconfig to connect to the cluster
                  when deploying the app.
                properties:
                  context:
                    description: Context is the kubeconfig context.
                    nullable: true
                    properties:
                      name:
                        description: Name is the name of the kubeconfig context. e.g.
                          giantswarm-12345.
                        type: string
                    required:
                    - name
                    type: object
                  inCluster:
                    description: InCluster is a flag for whether to use InCluster
                      credentials. When true the context name and secret should not
                      be set.
                    type: boolean
                  secret:
                    description: Secret references a secret containing the kubconfig.
                    nullable: true
                    properties:
                      name:
                        description: Name is the name of the secret containing the
                          kubeconfig, e.g. app-operator-kubeconfig.
                        type: string
                      namespace:
                        description: Namespace is the namespace of the secret containing
                          the kubeconfig, e.g. giantswarm.
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                required:
                - inCluster
                type: object
              name:
                description: Name is the name of the app to be deployed. e.g. kubernetes-prometheus
                type: string
              namespace:
                description: Namespace is the namespace where the app should be deployed.
                  e.g. monitoring
                type: string
              namespaceConfig:
                description: NamespaceConfig is the namespace config to be applied
                  to the target namespace when the app is deployed.
                nullable: true
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: Annotations is a string map of annotations to apply
                      to the target namespace.
                    nullable: true
                    type: object
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels is a string map of labels to apply to the
                      target namespace.
                    nullable: true
                    type: object
                type: object
              userConfig:
                description: UserConfig is the user config to be applied when the
                  app is deployed.
                nullable: true
                properties:
                  configMap:
                    description: ConfigMap references a config map containing user
                      values that should be applied to the app.
                    nullable: true
                    properties:
                      name:
                        description: Name is the name of the config map containing
                          user values to apply, e.g. prometheus-user-values.
                        type: string
                      namespace:
                        description: Namespace is the namespace of the user values
                          config map on the management cluster, e.g. 123ab.
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                  secret:
                    description: Secret references a secret containing user secret
                      values that should be applied to the app.
                    nullable: true
                    properties:
                      name:
                        description: Name is the name of the secret containing user
                          values to apply, e.g. prometheus-user-secret.
                        type: string
                      namespace:
                        description: Namespace is the namespace of the secret, e.g.
                          kube-system.
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                type: object
              version:
                description: Version is the version of the app that should be deployed.
                  e.g. 1.0.0
                type: string
            required:
            - catalog
            - kubeConfig
            - name
            - namespace
            - version
            type: object
          status:
            description: Status Spec part of the App resource. Initially, it would
              be left as empty until the operator successfully reconciles the helm
              release.
            properties:
              appVersion:
                description: AppVersion is the value of the AppVersion field in the
                  Chart.yaml of the deployed app. This is an optional field with the
                  version of the component being deployed. e.g. 0.21.0. https://helm.sh/docs/topics/charts/#the-chartyaml-file
                type: string
              release:
                description: Release is the status of the Helm release for the deployed
                  app.
                properties:
                  lastDeployed:
                    description: LastDeployed is the time when the app was last deployed.
                    format: date-time
                    nullable: true
                    type: string
                  reason:
                    description: Reason is the description of the last status of helm
                      release when the app is not installed successfully, e.g. deploy
                      resource already exists.
                    type: string
                  status:
                    description: Status is the status of the deployed app, e.g. DEPLOYED.
                    type: string
                required:
                - status
                type: object
              version:
                description: Version is the value of the Version field in the Chart.yaml
                  of the deployed app. e.g. 1.0.0.
                type: string
            required:
            - appVersion
            - release
            - version
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
