- op: add
  path: /spec/validation/openAPIV3Schema/properties/metadata
  value:
    properties:
      name:
        type: string
        pattern: ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$
    type: object
